name: Update README

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  activity:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Add activity to readme
        uses: Readme-Workflows/recent-activity@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
