name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          CODE_LANG: rust
          SHOW_TITLE: true
          SHOW_TIME: true
          SHOW_TOTAL: true
          IGNORED_LANGUAGES: YAML JSON TOM
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
